require("dotenv").config();
const { web3 } = require("./web3");

const address = process.env.CONTRACT_ADDRESS;
const abi = [
    {
        constant: false,
        inputs: [{ name: "_address", type: "address" }],
        name: "removeAllowedTransactionCreator",
        outputs: [],
        payable: false,
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        constant: true,
        inputs: [],
        name: "getTransactionCount",
        outputs: [{ name: "", type: "uint256" }],
        payable: false,
        stateMutability: "view",
        type: "function",
    },
    {
        constant: false,
        inputs: [{ name: "_address", type: "address" }],
        name: "addAllowedTransactionCreator",
        outputs: [],
        payable: false,
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        constant: true,
        inputs: [{ name: "", type: "address" }],
        name: "allowedTransactionCreators",
        outputs: [{ name: "", type: "bool" }],
        payable: false,
        stateMutability: "view",
        type: "function",
    },
    {
        constant: false,
        inputs: [
            { name: "_id", type: "string" },
            { name: "_recordId", type: "string" },
            { name: "_operation", type: "string" },
            { name: "_performedBy", type: "string" },
            { name: "_description", type: "string" },
        ],
        name: "createTransaction",
        outputs: [],
        payable: false,
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        constant: true,
        inputs: [{ name: "", type: "address" }],
        name: "allowedTransactionViewers",
        outputs: [{ name: "", type: "bool" }],
        payable: false,
        stateMutability: "view",
        type: "function",
    },
    {
        constant: true,
        inputs: [{ name: "", type: "uint256" }],
        name: "transactions",
        outputs: [
            { name: "id", type: "string" },
            { name: "recordId", type: "string" },
            { name: "operation", type: "string" },
            { name: "performedBy", type: "string" },
            { name: "description", type: "string" },
            { name: "timeStamp", type: "uint256" },
        ],
        payable: false,
        stateMutability: "view",
        type: "function",
    },
    {
        constant: true,
        inputs: [],
        name: "clinicId",
        outputs: [{ name: "", type: "string" }],
        payable: false,
        stateMutability: "view",
        type: "function",
    },
    {
        constant: true,
        inputs: [],
        name: "clinicAdmin",
        outputs: [{ name: "", type: "address" }],
        payable: false,
        stateMutability: "view",
        type: "function",
    },
    {
        constant: true,
        inputs: [],
        name: "clinicName",
        outputs: [{ name: "", type: "string" }],
        payable: false,
        stateMutability: "view",
        type: "function",
    },
    {
        constant: false,
        inputs: [{ name: "_address", type: "address" }],
        name: "addAllowedTransactionViewer",
        outputs: [],
        payable: false,
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        constant: false,
        inputs: [{ name: "_address", type: "address" }],
        name: "removeAllowedTransactionViewer",
        outputs: [],
        payable: false,
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            { name: "_clinicName", type: "string" },
            { name: "_clinicId", type: "string" },
        ],
        payable: false,
        stateMutability: "nonpayable",
        type: "constructor",
    },
];
const instance = new web3.eth.Contract(abi, address);

module.exports = { instance };
